export const AUTH_CONSTANTS = {
    AUTH_SERVICE : 'AUTH_SERVICE',
    REGISTRATION_COMMAND: 'REGISTRATION_COMMAND',
    ACCOUNT_REPOSITORY: 'ACCOUNT_REPOSITORY',
    CRYPTO_SERVICE: 'CRYPTO_SERVICE',
    JWT_SERVICE: 'JWT_SERVICE',
    ENTRANCE_TOKEN_REPOSITORY: 'ENTRANCE_TOKEN_REPOSITORY',
}

export const INFRASTRUCTURE_CONSTANTS = {
    CONFIG : 'CONFIG',
    PG: 'PG',
    REDIS: 'REDIS',
}

export const FILE_CONSTANTS = {
    FILE_SERVICE : 'FILE_SERVICE',
    FILE_STORAGE_SERVICE: 'FILE_STORAGE_SERVICE',
    FILE_PATH_REPOSITORY: 'FILE_PATH_REPOSITORY'
}

export const EVENT_CONSTANTS = {
    EVENT_BUS : 'EVENT_BUS',
}

export const CHAT_CONSTANTS = {
    CHAT_SERVICE : 'CHAT_SERVICE',
    CHAT_GATEWAY :  'CHAT_GATEWAY'
}